### ISSUE TITLE
Unusable with Ambigous Timezone

### ISSUE THREAD

**Issue by jgoetze** [zverok/wheretz#6] opened 2019-02-03 11:53 UTC
https://github.com/zverok/wheretz/blob/9175c9487227e7dd04f323854b681e4de11cb2fa/lib/wheretz.rb#L94

Hello, 
when looking up '69.11.125.60', it fails with "ambigous" timezone. (Btw it is misspelled)

There are two zones as result: ["America/Regina", "America/Swift_Current"]

It is not possible to work with those zones after the error.

Could you add the result to the exception as variable or provide a method/variable like "last_lookup_result" where to get the results after rescuing or provide a separate method like "lookup_all" where it always returns an array?

Thanks in advance.

**Comment by deepj** [comment] 2019-06-27 14:55
@zverok Hello I have a case how to reproduce this

I have the following address `Swift Current, SK, CA`. I use `Geocoder.search('Swift Current, SK, CA')`. I'm getting this coordinates `[50.28337, -107.80135]`.

I hope this help you to reproduce it.

**Comment by zverok** [comment] 2019-06-28 12:35
Fixed in 0.0.3, thanks for reporting.
```ruby
WhereTZ.lookup(50.28337, -107.80135)
# => ["America/Regina", "America/Swift_Current"] 
```
(0.0.3 also have dataset updated to the very latest data from timezone-builder)

**Closed by zverok** 2019-06-28 12:35 UTC

**Comment by deepj** [comment] 2019-06-28 16:01
@zverok Great! If possible to have some option in `#lookup` which causes returning always the first timezone in a case of ambiguous timezones? Or better, allow to added a `proc `to process it itself at least.

I'm processing some addresses of some objects and I need to added to their timezones. And it's okay if the timezone is not 100% accurate. So I'm expecting only a string as a result.

In case of a `proc` I would be happy to have something like

```ruby
WhereTZ.lookup(50.28337, -107.80135, ambigous: proc(&:first))
# => "America/Regina"
```

**Comment by zverok** [comment] 2019-06-29 18:38
@deepj I am willing to accept a PR, let's put it this way.
TBH, I don't have a lot of time nowadays for evolving the library, just feel obliged to keep it useful (if I had, I'd probably first take a look at the algorithms inside, because a grew to understand that current performance shouldn't be considered "quite fast" as readme claims :))
